version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    rebase-strategy: auto
    schedule:
      interval: cron
      cronjob: "0 9 * * MON-THU"
      timezone: "Europe/Berlin"
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      actions-patches:
        patterns: ["*"]
        update-types: ["minor", "patch"]

  - package-ecosystem: "terraform"
    directory: "/infra"
    open-pull-requests-limit: 10
    rebase-strategy: auto
    schedule:
      interval: cron
      cronjob: "15 9 * * TUE-THU"
      timezone: "Europe/Berlin"
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      terraform:
        patterns: ["*"]
        update-types: ["minor", "patch"]

  - package-ecosystem: "npm"
    directory: "/02_central"
    open-pull-requests-limit: 10
    rebase-strategy: auto
    schedule:
      interval: cron
      cronjob: "30 9 * * MON-THU"
      timezone: "Europe/Berlin"
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      02_central:
        patterns: ["*"]
        update-types: ["minor", "patch"]
    ignore:
      - dependency-name: "@types/node"
        versions: ["25.x"]

  - package-ecosystem: "npm"
    directory: "/04_frontend"
    open-pull-requests-limit: 10
    rebase-strategy: auto
    schedule:
      interval: cron
      cronjob: "30 10 * * MON-THU"
      timezone: "Europe/Berlin"
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      04_frontend:
        patterns: ["*"]
        update-types: ["minor", "patch"]
    ignore:
      - dependency-name: "@types/node"
        versions: ["25.x"]

  - package-ecosystem: "npm"
    directory: "/common"
    open-pull-requests-limit: 10
    rebase-strategy: auto
    schedule:
      interval: cron
      cronjob: "30 11 * * MON-THU"
      timezone: "Europe/Berlin"
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      common:
        patterns: ["*"]
        update-types: ["minor", "patch"]
